// Generated by: setup
// TypeWriter: stringer
// Directive: +test on Number

package main

import (
	"fmt"
)

const _Number_name = "OneTwoThree"

var _Number_index = [...]uint8{0, 3, 6, 11}

func (i Number) String() string {
	i -= 1
	if i < 0 || i+1 >= Number(len(_Number_index)) {
		return fmt.Sprintf("Number(%d)", i+1)
	}
	return _Number_name[_Number_index[i]:_Number_index[i+1]]
}
