// Generated by: setup
// TypeWriter: stringer
// Directive: +test on Unum

package main

import (
	"fmt"
)

const (
	_Unum_name_0 = "u0u1u2"
	_Unum_name_1 = "u_2u_1"
)

var (
	_Unum_index_0 = [...]uint8{0, 2, 4, 6}
	_Unum_index_1 = [...]uint8{0, 3, 6}
)

func (i Unum) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _Unum_name_0[_Unum_index_0[i]:_Unum_index_0[i+1]]
	case 253 <= i && i <= 254:
		i -= 253
		return _Unum_name_1[_Unum_index_1[i]:_Unum_index_1[i+1]]
	default:
		return fmt.Sprintf("Unum(%d)", i)
	}
}
